version: '3.1'

services:
  jrtb-bot:
    depends_on:
      - jrtb-db
    build:
      context: .
    environment:
      BOT_DB_USERNAME: ${BOT_DB_USERNAME}
      BOT_DB_PASSWORD: ${BOT_DB_PASSWORD}
    restart: always
  jrtb-db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: ${BOT_DB_USERNAME}
      MYSQL_PASSWORD: ${BOT_DB_PASSWORD}
      MYSQL_DATABASE: 'dev_jrtb_db'
      MYSQL_ROOT_PASSWORD: '220491Ira!'
    ports:
      - '3307:3307'
    expose:
      - '3307'